/*
 * DO NOT MODIFY.
 * This file was generated by ms_gen_mvxv_h.py
 */
#define MVXV_HEAD_VER   "4"
#define MVXV_LIB_TYPE   "##"
#define MVXV_CHIP_ID    "I2M#"
#define MVXV_CHANGELIST "g2804e3c"
#define MVXV_COMP_ID    "KL_LX409##"
#define MVXV_EXT        "[BR:main]"

