include $(PROJ_ROOT)/release/customer_tailor/ipc_default.mk
interface_bar:=disable
interface_sys:=enable
interface_vif:=enable
interface_vpe:=enable
interface_venc:=enable
interface_divp:=enable
interface_ai:=enable
interface_rgn:=enable
interface_ao:=enable
interface_disp:=disable
interface_sd:=disable
interface_panel:=disable
interface_shadow:=enable
interface_vdf:=enable
interface_sensor:=enable
interface_ldc:=disable
interface_isp:=enable
interface_iqserver:=enable
os_linux:=disable
os_rtos:=enable
verify_bar:=disable
verify_sys:=disable
verify_venc:=disable
verify_sys_divp:=disable # need remove rtos header file
verify_rgn:=disable  # need remove rtos header file
verify_stream_dump:=disable
verify_rtk_linux_ai_demo:=enable
verify_rtk_linux_mi_demo:=enable
mhal_ldc:=disable
mhal_imi_heap:=disable
mhal_panel:=disable
mhal_disp:=disable
mhal_hdmitx:=disable
mhal_ge:=disable
mhal_init:=disable
